config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'instruction#index'

  get 'instruction/index'
  get 'instruction/exit'

  resources :users, except: %i(destroy)
  post 'session' => 'session#create'
  delete 'session' => 'session#destroy'

  resources :items do
    get :recommendation, on: :collection
    post :rating, on: :member
    patch :opinion, on: :member
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/concerns/constants.rb
module Constants
  DEPARTMENTS = {
    general:     0,
    information: 1,
    electronics: 2,
    mechanical:  3,
    system:      4,
    chemistry:   5,
    advanced_ei: 6,
    advanced_ms: 7,
    advanced_c:  8,
  }

  DEPARTMENTS_LOCALE = DEPARTMENTS.keys.map{|department|
    [I18n.t("activerecord.modules.constants.departments.#{department.to_s}"), department.to_s]
  }
end

app/models/feature.rb
class Feature < ActiveRecord::Base
  belongs_to :item
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :features
  has_many :ratings
  has_many :opinions

  accepts_nested_attributes_for :features
  accepts_nested_attributes_for :opinions

  enum department: Constants::DEPARTMENTS

  scope :refine, lambda {|arg|
    if arg[:grade] && arg[:department]
      where(grade: arg[:grade], department: Constants::DEPARTMENTS[arg[:department].to_sym])
    elsif arg[:grade]
      where(grade: arg[:grade])
    elsif arg[:department]
      where(department: Constants::DEPARTMENTS[arg[:department].to_sym])
    else
      all
    end
  }
end

app/models/opinion.rb
class Opinion < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
  belongs_to :subject
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
end

app/models/similarity.rb
class Similarity < ActiveRecord::Base
  belongs_to :subject, class_name: 'User'
  belongs_to :target, class_name: 'User'
end

app/models/subject.rb
class Subject < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :targeted_similarities, class_name: 'Similarity', foreign_key: 'target_id'
  has_many :ratings, -> { where(taken: true) }
  has_many :rated_items, through: :ratings, class_name: 'Item', source: 'item'

  has_secure_password

  enum department: Constants::DEPARTMENTS

  validates :email, :name, :department, :grade, presence: true
  validates :email, uniqueness: true

  def rated_items_and(items)
    self.rated_items.joins(:ratings).merge(Rating.where(item: items, taken: true)).uniq
  end

  def unrated_items(from = :all)
    if from == :own
      items = Item.refine(grade: self.grade, department: self.department)
    else
      items = Item.all
    end

    items - rated_items
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private
  def current_user
    begin
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue
      session[:user_id] = nil
    end
  end

  def authenticate_user!
    redirect_to root_path, alert: 'ログインしてください。' unless current_user
  end

  def unauthenticate_user!
    redirect_to root_path, notice: 'ログアウトしてください。' if current_user
  end
end

app/controllers/instruction_controller.rb
class InstructionController < ApplicationController
  def index
    if current_user
      @next_item = current_user.unrated_items.sample
    else
      @user = User.new
    end
  end

  def exit
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  protect_from_forgery except: %i(create)
  before_action :authenticate_user!, except: %i(create)
  before_action :set_items, only: %i(index)

  def index
    @rated_items = current_user.rated_items
  end

  def show
    @item = Item.find(params[:id])
    @rating = Rating.find_by(item: @item, user: current_user)
    @next_item = current_user.unrated_items.sample
    @unrated_items_num = current_user.unrated_items.size
    @subjects = Subject.all
    @subjects.each do |s|
      @item.opinions.build(subject: s)
    end
  end

  def create
    @item = Item.new(item_params)

    @result = @item.save
    render "create", formats: [:json], handlers: [:jbuilder]
  end

  def rating
    @item = Item.find(params[:id])
    @rating = Rating.find_or_initialize_by(item: @item, user: current_user)

    if params[:value].present?
      @rating.value = params[:value]
      @rating.taken = true
    else
      @rating.taken = false
    end

    @previous_prediction = @rating.prediction
    @rating.prediction = false

    if @rating.save
      respond_to do |format|
        format.html do
          if @previous_prediction
            redirect_to recommendation_items_path
          else
            if @next_item = current_user.unrated_items.sample
              redirect_to item_path(@next_item)
            else
              redirect_to items_path, notice: "全てのアイテムを評価しました。"
            end
          end
        end
        format.js
      end
    else
      redirect_to item_path(@item), alert: "不正な値です。"
    end
  end

  def recommendation
    @ratings = Rating.where(user: current_user, prediction: true).where('value >= ?', 4.0).order('value desc')
  end

  def opinion
    @item = Item.find(params[:id])
    @item.update(opinion_params)
    @next_item = current_user.unrated_items.sample
    if @next_item
      redirect_to item_path(@next_item)
    else
      redirect_to items_path
    end
  end

  private
    def set_items
      @grade = params[:grade].presence
      @department = params[:department].presence
      @items = current_user.rated_items
    end

    def item_params
      params.require(:item).permit(:year, :grade, :department, :name, :english_name, :term, :credit_num, :credit_requirement, :provided_by, features_attributes: [:name, :content])
    end

    def opinion_params
      params.require(:item).permit(opinions_attributes: [:subject_id, :value, :user_id])
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'ログインしました。'
    else
      redirect_to root_path, alert: 'ログインに失敗しました。入力情報が間違っています。'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'ログアウトしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :unauthenticate_user!, only: %i(new create)
  before_action :authenticate_user!, only: %i(edit update)

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      if @next_item = @user.unrated_items.sample
        redirect_to item_path(@next_item), notice: '被験者情報が登録されました。これより各科目について評価を入力してください。'
      else
        redirect_to instruction_exit_path, notice: '実験対象の科目がありませんでした。'
      end
    else
      render 'instruction/index'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update(user_params)
      redirect_to root_path, notice: "変更しました。"
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :grade, :department)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/instruction/exit.html.slim
.contents
  h2 Instruction#exit
  p Find me in app/views/instruction/exit.html.slim

app/views/instruction/index.html.slim
= content_for(:main_header) do
  .contents
    h2 Instruction#index

.contents
  - if current_user
    .content
      = "ようこそ、#{current_user.name}さん"

    .content
      h3 = "#{current_user.name}さんの登録情報"
      dl
        dt 所属学科・専攻
        dd
          - if current_user.department
            = t("activerecord.modules.constants.departments.#{current_user.department}")
          - else
            '登録情報なし
        dt 学年
        dd = "#{current_user.grade}年"

    .content
      div = link_to '推薦リスト', recommendation_items_path

  - else
    .content
      p
        '本日は被験者実験にご参加いただき、ありがとうございます。
        '本実験では皆様の科目に対する嗜好情報を収集します。
        '嗜好情報は次の項目についての総合的な評価を5段階の値で入力していただきます。
      ul
        li 授業が楽しかった。
        li 興味のある分野である。
        li 就職・進学で同分野を考えたい。

      p
        '被験者情報を登録していただくと実験スタートとなります。
        '入力していただいた情報は個人が特定されないように加工して研究に活用させていただきます。
        'このことに同意いただければ、実験をはじめてください。

    .content
      h2 ログイン
      = form_tag session_path
        div
          label メールアドレス
          = text_field_tag :email
        div
          label パスワード
          = password_field_tag :password
        div
          = submit_tag 'ログイン'

    .content
      h2 ユーザ登録

      = simple_form_for @user do |f|
        = render partial: 'users/form', locals: {f: f}

app/views/items/_list.html.slim
- items.each do |item|
  .content.listed_item
    .rating
      - rating = current_user.ratings.find_by(item: item)
      - rating_val = rating.present? && rating.value ? rating.value : 0
      - 5.times do |i|
        - value = i + 1
        - if rating_val < value
          div class="value item_#{item.id} val_#{value}"
            = link_to image_tag('', size: '25x25', class: 'star_empty'), rating_item_path(item, value: value), method: 'post', remote: true

        - else
          div class="value item_#{item.id} val_#{value} persisted"
            = link_to  image_tag('', size: '25x25', class: 'star'), rating_item_path(item, value: value), method: 'post', remote: true

    = link_to item.name, item_path(item)

app/views/items/index.html.slim
.contents
  h2 アイテム一覧

  /= form_tag
    .input.select.optional.form-group
       = select_tag 'item_grade_refine', options_for_select([["学年で絞り込む", nil], ["1年生", 1], ["2年生", 2], ["3年生", 3], ["4年生", 4], ["5年生", 5]], selected: @grade), class: 'select optional form-control'
    .input.select.optional.form-group
      = select_tag 'item_department_refine', options_for_select([["学科で絞り込む", nil]].concat(Constants::DEPARTMENTS_LOCALE), selected: @department), class: 'select optional form-control'

  #items
    = render partial: 'items/list', locals: {items: @items}

app/views/items/index.js.erb
$('#items').html("<%= j(render partial: 'items/list', locals: {items: @items}) %>");

app/views/items/rating.js.erb
// rating value's link container
$target_val = $(".item_<%= j(@item.to_param) %>.val_<%= j(params[:value].to_s) %>");

// make stars bigger than the value empty
// and remove class .persisted
$target_val.nextAll().find('img').addClass('star_empty');
$target_val.nextAll().find('img').removeClass('star');
$target_val.nextAll().removeClass('persisted');

// make stars equal to or smaller than the value colored
// and add class .persisted
$target_val.prevAll().find('img').addClass('star');
$target_val.prevAll().find('img').removeClass('star_empty');

$target_val.find('img').addClass('star');
$target_val.find('img').removeClass('star_empty');

$target_val.prevAll().addClass('persisted');
$target_val.addClass('persisted');

app/views/items/recommendation.html.slim
.contents
  - @ratings.each do |rating|
    - item = rating.item
    .content
      = link_to item.name, item

app/views/items/show.html.slim
.contents
  h2 = "#{@item.name}(#{@item.english_name})"

  .content
    .rating
      - rating_val = @rating.present? && @rating.value ? @rating.value : 0
      - 5.times do |i|
        - value = i + 1
        - if rating_val < value
          - div_class = "value item_#{@item.id} val_#{value}"
          - star_img = image_tag('', size: '25x25', class: 'star_empty')
        - else
          - div_class = "value item_#{@item.id} val_#{value} persisted"
          - star_img = image_tag('', size: '25x25', class: 'star')

        - if @rating.prediction
          div class="#{div_class}"
            = link_to star_img, rating_item_path(@item, value: value), method: :post
        - else
          - if value > 2
            div class="#{div_class}"
              = link_to star_img, rating_item_path(@item, value: value), method: :post
          - else
            div class="#{div_class}"
              = link_to star_img, '#', value: value, item_id: @item.id

      = link_to '履修していない', rating_item_path(@item), style: "display: block;", method: :post

    .opinion
      h3 否定的な評価を入力した主たる要因となった特徴を入力してください（複数回答可）
      = form_for @item, url: opinion_item_path(@item) do |f|
        = f.fields_for :opinions do |of|
          div
            = of.hidden_field :subject_id, value: of.object.subject.id
            = of.hidden_field :user_id, value: current_user.id
            = of.check_box :value
            = of.label of.object.subject.title

        div style="display:block;" = f.submit

    - if @next_item
      '未評価の科目数:&nbsp;
      = content_tag :span, @unrated_items_num, id: 'unrated_items_num'
    - elsif @rating.prediction
      = link_to "推薦一覧", recommendation_items_path
    - else
      = link_to "一覧", items_path
  .content
    dl
      dt 教官
      dd = @item.provided_by
      dt 学年
      dd = @item.grade
      dt 学科
      dd = t("activerecord.modules.constants.departments.#{@item.department}")
      dt 期間
      dd = @item.term
      dt 単位
      dd = "#{@item.credit_num}(#{@item.credit_requirement})"

  - @item.features.each do |feature|
    .content
      h3 = feature.name
      div = feature.content

app/views/layouts/application.html.slim
doctype html
html lang='ja'
  head
  title RS4NNCT
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

  body
    .wrapper
      .header
        = render partial: 'shared/header'
      .main
        = yield(:main_header)
        .contents.messages
          = flash[:notice]
          = flash[:alert]
        = yield

app/views/shared/_header.html.slim
.contents
  h1 = link_to 'RS4NNCT', root_path

app/views/users/_form.html.slim
= f.input :name
= f.input :email
= f.input :grade, collection: 1..5
= f.input :department, collection: Constants::DEPARTMENTS_LOCALE
= f.input :password, required: true
= f.input :password_confirmation, required: true
= f.submit

app/views/users/edit.html.slim
.contents
  h2 登録情報の変更

  = simple_form_for @user do |f|
    = render partial: 'users/form', locals: {f: f}

app/views/users/new.html.slim
.contents
  h2 ユーザ登録

  = simple_form_for @user do |f|
    = render partial: 'users/form', locals: {f: f}